# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mekswhy's Blog
tagline:          Be simple and stupid!
paginate:         5
baseurl:          /
author:
  name:           mekswhy
  email:          mekswhy@gmail.com

